services:
  - type: web
    name: nayon-alpha-signals
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST_TECHNICAL
        value: crypto-technical-analysis-indicator-apis-for-trading.p.rapidapi.com
      - key: RAPIDAPI_HOST_PRICE
        value: real-time-crypto-price-api.p.rapidapi.com
      - key: RAPIDAPI_HOST_TRADERS
        value: traders-hub-trading-signals5.p.rapidapi.com
      - key: RAPIDAPI_HOST_SELFTRADE
        value: selftrade.p.rapidapi.com
      - key: RAPIDAPI_HOST_STOCKTA
        value: stock-technical-analysis1.p.rapidapi.com
      - key: PORT
        value: 3000
